<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "media_artbdg"
 *
 * Auto generated by Extension Builder 2018-01-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'media_artbdg',
    'description' => 'Bibliothèque média de Anaïs Rodrigues, Dorian Giudice & Thomas Beaupertuis',
    'category' => 'plugin',
    'author' => 'Dorian Giudice, Thomas Beaupertuis, Anais Rodrigues',
    'author_email' => 'dorian.giudice@gmail.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
